-- Generated by CSharp.lua Compiler
local System = System
local Rew1nd
System.import(function (out)
  Rew1nd = out.Rew1nd
end)
System.namespace("Rew1nd", function (namespace)
  namespace.class("Extensions", function (namespace)
    local Rot47Decode
    Rot47Decode = function (str)
      return Rew1nd.Rot47.rot47_it(str)
    end
    return {
      Rot47Decode = Rot47Decode
    }
  end)
end)
