-- Generated by CSharp.lua Compiler
return function (path)
  return System.init({
    path = path,
    files = {
      "Extensions",
      "Program",
      "rot47"
    },
    types = {
      "Rew1nd.Extensions",
      "Rew1nd.Rot47",
      "ThouShallNotPass.Program"
    },
    Main = "ThouShallNotPass.Program.Main",
    assembly = {
      Company = "Rew1nd",
      Configuration = "Debug",
      FileVersion = "1.0.0.0",
      InformationalVersion = "1.0.0",
      Product = "Rew1nd",
      Title = "Rew1nd",
      Version = "1.0.0.0"
    }
  })
end
